# Autogenerated with 'nix run .#wrench'

{
  inputs = {
    nixpkgs = {
      url = "github:NixOS/nixpkgs/nixos-26.05";
    };
    treefmt-nix = {
      inputs = {
        nixpkgs = {
          follows = "nixpkgs";
        };
      };
      url = "github:numtide/treefmt-nix";
    };
    wrench = {
      inputs = {
        nixpkgs = {
          follows = "nixpkgs";
        };
      };
      url = "./wrench";
    };
  };
  outputs = inputs: inputs.wrench.lib.loadModules ./modules inputs;
}
