# Autogenerated with 'nix run .#drive'
{
  inputs = {
    easy-purescript-nix = {
      url = "github:justinwoo/easy-purescript-nix";
    };
    nixpkgs = {
      url = "github:NixOS/nixpkgs/nixos-26.05";
    };
    nixpkgs-unstable = {
      url = "github:NixOS/nixpkgs/nixos-unstable";
    };
    treefmt-nix = {
      inputs = {
        nixpkgs = {
          follows = "nixpkgs";
        };
      };
      url = "github:numtide/treefmt-nix";
    };
    wrench = {
      inputs = {
        nixpkgs = {
          follows = "nixpkgs";
        };
      };
      url = "github:StijnRuts/nix-wrench";
    };
  };

  outputs = inputs: inputs.wrench.lib.drive ./bolts.nix inputs;
}
