{
  lib,
  wrench,
  ...
}:
bolts: inputs:
let
  modules = lib.evalModules {
    modules = builtins.concatLists (
      map (p: lib.mapAttrsToListRecursive (_keys: path: path) (wrench.lib.collect p)) (
        (import bolts) wrench
      )
    );
    specialArgs = { inherit wrench; };
  };

  flakeTemplate = lib.generators.toPretty { } {
    inputs = modules.config.inputs // {
      wrench = {
        url = "github:StijnRuts/nix-wrench";
        inputs.nixpkgs.follows = "nixpkgs";
      };
    };
    outputs = "<outputs>";
  };

  flakeContents =
    "# Autogenerated with 'nix run .#drive'\n"
    +
      lib.replaceString "\"<outputs>\"" "inputs: inputs.wrench.lib.drive ./bolts.nix inputs"
        flakeTemplate;

  extra = {
    apps = builtins.listToAttrs (
      map (
        system:
        let
          pkgs = inputs.nixpkgs.legacyPackages.${system};
        in
        {
          name = system;
          value = {
            drive = {
              type = "app";
              meta.description = "Regenerate flake.nix";
              program = "${pkgs.writeShellScriptBin "drive" ''
                cat > flake.nix << 'EOF'
                ${flakeContents}
                EOF
              ''}/bin/drive";
            };
          };
        }
      ) modules.config.systems
    );
  };
in
lib.recursiveUpdate (modules.config.outputs inputs) extra
