{ lib, wrench, ... }:
bolts: inputs:
let
  modules = lib.evalModules {
    modules = builtins.concatLists (
      map (p: lib.mapAttrsToListRecursive (_keys: path: path) (wrench.lib.collect p)) (
        (import bolts) wrench
      )
    );
    specialArgs = { inherit wrench; };
  };

  isWrenchRepo = lib.hasPrefix (toString inputs.wrench.outPath) (toString bolts);

  flakeTemplate = lib.generators.toPretty { } {
    inputs = modules.config.inputs // {
      wrench = {
        url = if isWrenchRepo then "../.." else "github:StijnRuts/nix-wrench";
        inputs.nixpkgs.follows = "nixpkgs";
      };
    };
    outputs = "<outputs>";
  };

  flakeContents =
    "# Autogenerated with 'nix run .#drive'\n"
    +
      lib.replaceString "\"<outputs>\"" "inputs: inputs.wrench.lib.drive ./bolts.nix inputs"
        flakeTemplate;

  extra = {
    apps = wrench.lib.options."<system>" {
      inherit (modules.config) systems buildArgs;
      inherit inputs;
      transform = args: value: {
        drive = {
          type = "app";
          meta.description = "Regenerate flake.nix";
          program = "${args.pkgs.writeShellScriptBin "drive" ''
            cat > flake.nix << 'EOF'
            ${value}
            EOF
          ''}/bin/drive";
        };
      };
      value = _: flakeContents;
    };
  };
in
lib.recursiveUpdate (modules.config.outputs inputs) extra
