{ lib, wrench, ... }:
bolts: inputs:
let
  load =
    x:
    if builtins.isAttrs x then
      builtins.concatLists (lib.mapAttrsToList (_key: load) x)
    else if builtins.isList x then
      builtins.concatLists (map load x)
    else if builtins.isPath x then
      if lib.pathIsDirectory x then load (wrench.lib.collect x) else [ x ]
    else
      throw "Can not load type ${builtins.typeOf x} ${toString x}";

  modules = lib.evalModules {
    modules = load ((import bolts) wrench);
    specialArgs = { inherit wrench; };
  };

  isWrenchRepo = lib.hasPrefix (toString inputs.wrench.outPath) (toString bolts);

  flakeTemplate = lib.generators.toPretty { } {
    inputs = modules.config.inputs // {
      wrench = {
        url = if isWrenchRepo then "../.." else "github:StijnRuts/nix-wrench";
        inputs.nixpkgs.follows = "nixpkgs";
      };
    };
    outputs = "<outputs>";
  };

  flakeContents =
    "# Autogenerated with 'nix run .#drive'\n"
    +
      lib.replaceString "\"<outputs>\"" "inputs: inputs.wrench.lib.drive ./bolts.nix inputs"
        flakeTemplate;

  extra = {
    apps = wrench.lib.options."<system>" {
      inherit (modules.config) systems buildArgs;
      inherit inputs;
      transform = args: value: {
        drive = {
          type = "app";
          meta.description = "Regenerate flake.nix";
          program = "${args.pkgs.writeShellScriptBin "drive" ''
            cat > flake.nix << 'EOF'
            ${value}
            EOF
          ''}/bin/drive";
        };
      };
      value = _: flakeContents;
    };
  };
in
lib.recursiveUpdate (modules.config.outputs inputs) extra
