{
  lib,
  wrench,
  modulesDir,
}:
path: inp:
let
  expandPath =
    path:
    if lib.hasSuffix ".nix" (toString path) then
      [ path ]
    else
      builtins.filter (lib.hasSuffix ".nix") (lib.filesystem.listFilesRecursive path);

  modulePaths = builtins.concatLists (
    builtins.map expandPath (if builtins.isList path then path else [ path ])
  );

  inherit
    (
      (lib.evalModules {
        modules =
          modulePaths
          ++ (builtins.filter (lib.hasSuffix ".nix") (lib.filesystem.listFilesRecursive modulesDir));
        specialArgs = { inherit wrench; };
      })
    )
    config
    ;

  flakeTemplate = lib.generators.toPretty { } {
    inputs = config.inputs // {
      wrench = {
        url = "./wrench";
        inputs.nixpkgs.follows = "nixpkgs";
      };
    };
    outputs = "<outputs>";
  };

  flakeContents =
    "# Autogenerated with 'nix run .#wrench'\n\n"
    +
      lib.replaceString "\"<outputs>\"" "inputs: inputs.wrench.lib.loadModules ./modules inputs"
        flakeTemplate;

  extra = {
    apps = builtins.listToAttrs (
      builtins.map (
        system:
        let
          pkgs' = inp.nixpkgs.legacyPackages.${system};
        in
        {
          name = system;
          value = {
            wrench = {
              type = "app";
              meta.description = "Regenerate flake.nix";
              program = "${pkgs'.writeShellScriptBin "wrench" ''
                cat > flake.nix << 'EOF'
                ${flakeContents}
                EOF
              ''}/bin/wrench";
            };
          };
        }
      ) config.systems
    );
  };
in
lib.recursiveUpdate (config.outputs inp) extra
